features:
  num_workers: 1
  pin_memory: true
milvus:
  fields:
    - field_name: "frame_id"
      datatype: "VARCHAR"
      max_length: 100
      is_primary: true
    - field_name: "clip_feature"
      datatype: "FLOAT_VECTOR"
      dim: 512
    - field_name: "cluster_id"
      datatype: "INT64"
  indices:
    - field_name: "clip_feature"
      metric_type: "COSINE"
      index_type: "IVF_FLAT"
      index_name: "clip_index"
      params:
        nlist: 128
