# AIC25 Development Configuration
# Override settings for development environment

webui:
  host: "0.0.0.0"  # Allow external connections in dev
  port: 8000

# Enable detailed logging in development
logging:
  level: "DEBUG"
  
# Smaller batch sizes for development
webui:
  features:
    - name: "clip"
      batch_size: 8  # Smaller batch for dev
    - name: "sentence_transformer"
      batch_size: 16  # Smaller batch for dev

# Development-specific hardware settings
hardware:
  gpu:
    mixed_precision: false  # Disable for debugging
  cpu:
    num_threads: 4  # Limit threads in dev

# Enable all debugging features
distributed:
  service_discovery:
    enabled: true
    
# Development workspace
storage:
  workspace_dir: "./dev_workspace"